splash = false
wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/landscape/themify/tropical-wet/wp-l-15.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/landscape/themify/tropical-wet/wp-l-15.jpg
    fit_mode = cover
}
